### PR TITLE
add nf-prov

### PR DESCRIPTION
**Pull request by kubranarci**
- nf-prov is added
- nextflow version needed to be updated

### CODE REVIEW

**Review by drewjbeh — APPROVED** [review]
Looks good to me! Thanks Kübra

**Comment by kubranarci** [comment]
here is an example file for the manifest: 
[manifest_2024-10-10_11-16-29.bco.json](https://github.com/user-attachments/files/17326036/manifest_2024-10-10_11-16-29.bco.json)

**Comment by kubranarci** [comment]
Hey, @mauerk here is another nextflow pipeline, you can find manifest file in the commends.

**Comment by mauerk** [comment]
Thanks, @kubranarci !
Same as for platypus, the extension domain is empty, but everything else looks like we expect it.

**Comment by kubranarci** [comment]
if you find a way to add the extensions automatically to nextflow (non nf-core) pipelines it would be a great solution but I am not sure how.

**Comment by drewjbeh** [comment]
@kubranarci potentially see the discussion for platypus

**Pull request merged**
